#include<iostream.h>
#include<iomanip.h>
#include<conio.h>

/*
4654561651
*/
void main()
{
    clrscr();
    int sum=0,t=0,tempArr;
    int a,b;

    double var;
    string s = "svdfdsjknjk === --- ;;; lol";
    for(int i=0; i<1000; i++)
    {
        if(i%3==0|| i%5==0)
        {
            char temp;
            float varTemp;
            sum=sum+i;
        }
    }
    cout<<"sum = "<<sum;
    getch();
}
